### ISSUE TITLE
Error of missing definition to mlpmatrix

### ISSUE THREAD

**Issue by Jokerkakkoii** [elenabbbuenob/TSA-ActionSeg#1]
I got  an error like this when running tsa.py. And i noticed that the value of some paras are false. If theres connection between them and how could i fix this error. Look forward to your response :D
![(ZZY9N{}71~Y4 OKVV95@WH](https://github.com/elenabbbuenob/TSA-ActionSeg/assets/149364228/8a9a6f99-0c1c-4711-9727-6b440f5cf176)

**Comment by elenabbbuenob** [comment]
Hi,
I apologize for the oversight while I was working on the code. I simplified the names of some functions and forgot to ensure everything was correct. There's an error in the file model/mpl.py on line 12, where it should be **super(MLP, self).__init__()**. I'm sorry for any inconvenience this may have caused, and thank you for bringing it to my attention.

**Comment by Jokerkakkoii** [comment]
Thanks for your response and solution. But theres maybe another simlilar issue in the file losses/losses.py that it may need `super(kl_loss, self).init()` after line 10. I wonder if that issue really exists. Still look forward for your reply.

**Comment by elenabbbuenob** [comment]
Thank you for your message and for pointing out the potential issue in the file losses/losses.py. You're absolutely right. I have updated the git repository with the spelling errors, and I believe everything should work correctly now. Please feel free to check it out, and if you encounter any further issues or have additional questions, don't hesitate to let me know. Looking forward to hearing your feedback.
